# Generated by Django 2.2.5 on 2019-09-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='policy',
            table='policy',
        ),
    ]
