# Generated by Django 2.2.5 on 2019-09-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20190916_0751'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerpolicy',
            table='customer_policy',
        ),
    ]
