# Generated by Django 2.2.5 on 2019-09-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20190916_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpolicy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(max_length=100),
        ),
    ]
